#!/bin/bash

set -e

SCRIPT_DIR=$(CDPATH= cd "$(dirname "$BASH_SOURCE")" && pwd);

source "$SCRIPT_DIR/../../.env"

CDPATH=
cd $SCRIPT_DIR

[ -z "${DEV_PREFIX}" ] && echo "DEV_PREFIX is undefined" && exit 1

mkdir -p "${DEV_PREFIX}"

if [ ! -f /etc/ld.so.conf.d/shri314-myclient.conf ]
then
   sudo bash -s <<EEOM
echo "${DEV_PREFIX}" > /etc/ld.so.conf.d/shri314-myclient.conf
EEOM
fi

(
   PACKAGE=gmp-6.1.2

   if [ ! -f $DEV_PREFIX/.${PACKAGE}.done ]
   then
      rm -f ${PACKAGE}.tar.bz2 &&
         wget http://ftp.gnu.org/gnu/gmp/${PACKAGE}.tar.bz2 &&
         tar xjf ${PACKAGE}.tar.bz2 &&
         (
         cd ${PACKAGE} &&
            ./configure --prefix=$DEV_PREFIX/gcc6-deps/ &&
            make -j4 &&
            make install &&
            sudo ldconfig

      ) || exit 1

      touch $DEV_PREFIX/.${PACKAGE}.done
   fi

) || exit 1

hash -r

(
   PACKAGE=mpfr-3.1.5

   if [ ! -f $DEV_PREFIX/.${PACKAGE}.done ]
   then
      rm -f ${PACKAGE}.tar.bz2 &&
         wget http://ftp.gnu.org/gnu/mpfr/${PACKAGE}.tar.bz2 &&
         tar xjf ${PACKAGE}.tar.bz2 &&
         (
         cd ${PACKAGE} &&
            ./configure --prefix=$DEV_PREFIX/gcc6-deps/ --with-gmp=$DEV_PREFIX/gcc6-deps/ &&
            make -j4 &&
            make install &&
            sudo ldconfig

      ) || exit 1

      touch $DEV_PREFIX/.${PACKAGE}.done
   fi

) || exit 1

hash -r

(
   PACKAGE=mpc-1.0.3

   if [ ! -f $DEV_PREFIX/.${PACKAGE}.done ]
   then
      rm -f ${PACKAGE}.tar.gz &&
         wget http://ftp.gnu.org/gnu/mpc/${PACKAGE}.tar.gz &&
         tar xzf ${PACKAGE}.tar.gz &&
         (
         cd ${PACKAGE} &&
            ./configure --prefix=$DEV_PREFIX/gcc6-deps/ --with-gmp=$DEV_PREFIX/gcc6-deps/ --with-mpfr=$DEV_PREFIX/gcc6-deps/ &&
            make -j4 &&
            make install &&
            sudo ldconfig

      ) || exit 1

      touch $DEV_PREFIX/.${PACKAGE}.done
   fi

) || exit 1

hash -r

(
   PACKAGE=gcc-6.3.0

   if [ ! -f $DEV_PREFIX/.${PACKAGE}.done ]
   then
      rm -f ${PACKAGE}.tar.bz2 &&
         wget http://ftp.gnu.org/gnu/gcc/${PACKAGE}/${PACKAGE}.tar.bz2 &&
         tar xjf ${PACKAGE}.tar.bz2 &&
         rm -rf gcc6-stage &&
         mkdir gcc6-stage &&
         (
         set -e
         cd ./gcc6-stage/ &&
            ../${PACKAGE}/configure --prefix=$DEV_PREFIX/gcc6 --with-gmp=$DEV_PREFIX/gcc6-deps/ --with-mpfr=$DEV_PREFIX/gcc6-deps/ --with-mpc=$DEV_PREFIX/gcc6-deps/ \
            --enable-languages=c,c++ \
            --disable-bootstrap \
            --disable-multilib &&
            make -j4 &&
            make install &&
            sudo ldconfig

      ) || exit 1

      touch $DEV_PREFIX/.${PACKAGE}.done
   fi

) || exit 1

hash -r

(
   PACKAGE=cmake-3.8.0-rc1

   if [ ! -f $DEV_PREFIX/.${PACKAGE}.done ]
   then
      rm -f ${PACKAGE}.tar.gz &&
         wget --no-check-certificate https://cmake.org/files/v3.8/${PACKAGE}.tar.gz &&
         tar xzf ${PACKAGE}.tar.gz &&
         (
         cd ${PACKAGE} &&
            ./configure --prefix="$DEV_PREFIX/${PACKAGE}" &&
            make -j4 &&
            make install &&
            sudo ldconfig

      ) || exit 1

      touch $DEV_PREFIX/.${PACKAGE}.done
   fi

) || exit 1

hash -r

(
   PACKAGE=gdb-7.12.1

   if [ ! -f $DEV_PREFIX/.${PACKAGE}.done ]
   then
      rm -f ${PACKAGE}.tar.xz &&
         wget http://ftp.gnu.org/gnu/gdb/${PACKAGE}.tar.xz &&
         tar xJf ${PACKAGE}.tar.xz &&
         rm -rf gdb-stage &&
         mkdir gdb-stage &&
         (
         cd ./gdb-stage/ &&
            ../${PACKAGE}/configure --prefix="$DEV_PREFIX/gdb7" --enable-tui --enable-gdbtk --enable-gdbserver &&
            make -j4 &&
            make install &&
            sudo ldconfig

      ) || exit 1

      touch $DEV_PREFIX/.${PACKAGE}.done
   fi

) || exit 1
