#!/bin/bash

set -e

SCRIPT_DIR=$(CDPATH= cd "$(dirname "$BASH_SOURCE")" && pwd);

source "$SCRIPT_DIR/../../.env"

CDPATH=
cd $SCRIPT_DIR

(
   PACKAGE=$BOOST_NAME
   BOOST_VERSION=$(echo $BOOST_NAME | sed -e 's/boost_//' -e 's/_/./g')

   if [ ! -f $DEV_PREFIX/.${PACKAGE}.done ]
   then
      echo wget http://downloads.sourceforge.net/project/boost/boost/${BOOST_VERSION}/${PACKAGE}.tar.bz2 &&
         rm -rf ${PACKAGE} &&
         tar xjf ${PACKAGE}.tar.bz2 &&
         (
         cd ${PACKAGE} &&
            ./bootstrap.sh --prefix="$DEV_PREFIX/${PACKAGE}" &&
            ./b2 --without-python &&
            ./b2 --without-python install

      ) || exit 1

      touch $DEV_PREFIX/.${PACKAGE}.done
   fi

) || exit 1

hash -r

(
   PACKAGE=cpprestsdk

   if [ ! -f $DEV_PREFIX/.${PACKAGE}.done ]
   then
      [ ! -d cpprestsdk ] && git clone https://github.com/Microsoft/cpprestsdk
      [ -d cpprestsdk ] &&
         (
         cd ${PACKAGE}/Release &&
            cmake -DBUILD_SHARED_LIBS=OFF -DBoost_INCLUDE_DIR=$DEV_PREFIX/$BOOST_NAME/include -DCMAKE_INSTALL_PREFIX=$DEV_PREFIX . &&
            make -j4 &&
            make install

      ) || exit 1

      touch $DEV_PREFIX/.${PACKAGE}.done
   fi

) || exit 1

hash -r
